#!/bin/sh
####################################################################
# Put Personal Design to TRAC Enviroment
# Author: Rodrigo Augosto C. (coto) <contact@protoboard.cl>
# URL: http://protoboard.cl
# Created: Mar 5, 2010
####################################################################

echo "Distro to implement: (1) RHEL, (2) CentOs:"
read distro

while [[ ! $distro =~ ^1|2$ ]]; do
	echo "Choose a option's number [1] RHEL, [2] CentOs:"
	read distro
done

if [ $distro = 1 ]; then
    TracVers="Trac-0.11.7rc1-py2.4.egg"
    RepoPath="http://svn.epson.cl/environment/trunk/trac"
else
	TracVers="Trac-0.11.7-py2.4.egg"
	RepoPath="http://svn.protoboard.cl/protoboard/trunk/trac_environment/trac"
fi

####################################################################
# Backup Theme Trac
####################################################################
datetime=$(date +%Y%m%d%H%M%S)
mkdir -p /mnt/backup/trac_backup_$datetime
cp -r /usr/lib/python2.4/site-packages/$TracVers/trac /mnt/backup/trac_backup_$datetime/$TracVers

# Put Projects Customization at all
svn export $RepoPath /usr/lib/python2.4/site-packages/$TracVers/trac --force
